version: '3.8'

services:
  # OpenWebUI - 오픈소스 웹 인터페이스
  openwebui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      # - WEBUI_AUTH=true
      # - WEBUI_DATABASE_PATH=/app/backend/data/database.sqlite
      - OPENAI_API_BASE_URL=http://pipelines:9099
      - OPENAI_API_KEY=0p3n-w3bu!
    volumes:
      - openwebui-data:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - pipelines
    networks:
      - ai-network

  # Pipelines - OpenWebUI 플러그인 프레임워크
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    restart: unless-stopped
    ports:
      - "9099:9099"
    volumes:
      # - pipelines-data:/app/pipelines
      - ./pipelines:/app/pipelines
    environment:
      - APISERVER_HOST=api-server:8000
      - PIPELINES_DIR=/app/pipelines
      # 필요한 경우 특정 파이프라인 URL 추가 (주석 해제 후 사용)
      # - PIPELINES_URLS=https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py
    networks:
      - ai-network

  api-server:
    build:
      context: .
      dockerfile: images/api-server/Dockerfile
    container_name: api-server
    restart: unless-stopped
    ports:
      - "${APISERVER_PORT_EXTERNAL}:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
    networks:
      - ai-network

volumes:
  openwebui-data:
  # pipelines-data:

networks:
  ai-network:
    driver: bridge 